'use client';

import React from 'react';
import { motion } from 'motion/react';
import { Sparkles } from 'lucide-react';

interface AIAdviceCardProps {
  advice: string;
}

export const AIAdviceCard = ({ advice }: AIAdviceCardProps) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, delay: 0.2, ease: [0.22, 1, 0.36, 1] }}
      className="w-full relative group"
    >
      {/* Animated Gradient Border */}
      <div className="absolute -inset-[1px] bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 rounded-[2rem] opacity-30 group-hover:opacity-60 blur-[2px] transition-opacity duration-500" />
      
      <div className="relative bg-slate-900/60 backdrop-blur-2xl border border-white/10 rounded-[2rem] p-6 overflow-hidden">
        {/* Background Sparkle Decoration */}
        <div className="absolute top-0 right-0 p-6 opacity-10 group-hover:opacity-20 transition-opacity">
          <Sparkles className="w-12 h-12 text-blue-400" />
        </div>

        <div className="flex items-center space-x-3 mb-4">
          <div className="bg-gradient-to-br from-blue-500 to-purple-600 p-2 rounded-xl shadow-lg shadow-blue-500/20">
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <span className="text-xs font-black text-blue-200 uppercase tracking-[0.3em]">AI Personal Advice</span>
        </div>
        
        <p className="text-xl leading-relaxed text-blue-50 font-medium italic relative z-10">
          &quot;{advice}&quot;
        </p>
        
        <div className="mt-4 flex items-center space-x-2">
          <div className="w-1.5 h-1.5 rounded-full bg-blue-400 animate-pulse" />
          <span className="text-[10px] font-bold text-blue-400/60 uppercase tracking-widest">Generated by Gemini AI</span>
        </div>
      </div>
    </motion.div>
  );
};
