'use client';

import React from 'react';
import { motion } from 'motion/react';
import { Sparkles } from 'lucide-react';
import BentoCard from './BentoCard';

interface AIInsightProps {
  advice: string;
}

const AIInsight: React.FC<AIInsightProps> = ({ advice }) => {
  const isLoading = advice === 'Sedang menganalisis cuaca...';
  return (
    <BentoCard isAI className="p-8 md:p-10 flex flex-col justify-between min-h-[300px] md:min-h-[350px]" delay={0.2}>
      <div className="flex items-center space-x-3">
        <div className="bg-gradient-to-br from-blue-500 to-purple-600 p-2.5 rounded-xl shadow-lg shadow-blue-500/30">
          <Sparkles className="w-4 h-4 text-white" />
        </div>
        <span className="text-[9px] md:text-[10px] font-black text-white/40 uppercase tracking-[0.3em]">AI Personal Advice</span>
      </div>
      <div className="flex-1 flex items-center py-4">
        {isLoading ? (
          <div className="space-y-3 w-full">
            <div className="h-4 bg-white/10 rounded-full animate-pulse w-full" />
            <div className="h-4 bg-white/10 rounded-full animate-pulse w-4/5" />
            <div className="h-4 bg-white/10 rounded-full animate-pulse w-3/5" />
          </div>
        ) : (
          <motion.p key={advice} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}
            className="text-lg md:text-xl leading-relaxed text-white/90 font-medium italic">
            &ldquo;{advice}&rdquo;
          </motion.p>
        )}
      </div>
      <div className="flex items-center space-x-2">
        <div className="w-1.5 h-1.5 rounded-full bg-blue-400 animate-pulse" />
        <span className="text-[9px] md:text-[10px] font-bold text-white/30 uppercase tracking-widest">Generated by Groq AI</span>
      </div>
    </BentoCard>
  );
};

export default AIInsight;