'use client';

import React from 'react';
import { motion } from 'motion/react';
import { Sparkles } from 'lucide-react';

interface AIInsightProps { advice: string; }

const AIInsight: React.FC<AIInsightProps> = ({ advice }) => (
  <motion.div
    initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
    className="bg-slate-900/60 backdrop-blur-2xl border border-white/15 rounded-3xl p-6 flex gap-4 items-start"
  >
    <div className="w-9 h-9 rounded-2xl bg-gradient-to-br from-violet-500 to-blue-500 flex items-center justify-center shrink-0 shadow-lg shadow-violet-500/20">
      <Sparkles className="w-4 h-4 text-white" />
    </div>
    <div>
      <p className="text-[9px] font-black text-white/50 uppercase tracking-widest mb-2">AI Personal Advice</p>
      <p className="text-sm text-white/80 leading-relaxed font-medium italic">"{advice}"</p>
      <p className="text-[9px] text-white/35 font-bold uppercase tracking-widest mt-3">· Generated by Groq AI</p>
    </div>
  </motion.div>
);

export default AIInsight;